### ISSUE TITLE
Notification failures with `jq` related error

### ISSUE THREAD

**Issue by leecalcote** [layer5io/trigger-remote-provider-action#1]
#### Description
the jq failure in the Notify Providers workflows traces back to the use of jq in the action - https://github.com/layer5io/trigger-remote-provider-action/blob/dbd2e5f6b083b989cdb43f0bdcb57a70cf7d3658/run.sh#L28

**Comment by kumarabd** [comment]
https://github.com/layer5io/trigger-remote-provider-action/commit/664164d73957b47a323ba796b4034270c32597f7
https://github.com/layer5io/trigger-remote-provider-action/commit/df652a33f01a648f54e6f042a069e96306ab44c8

This is done to fix the error message with more info. Actual issue is fixed in the meshery workflow file.

**Comment by leecalcote** [comment]
Thank you, @kumarabd 💯
